server:
  port: 8001

spring:
  application:
    name: microservice-dept
  datasource:
    url: jdbc:mysql://localhost:3306/hand_train             # 数据库名称
    username: root
    password: 231023

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
