spring:
  profiles:
    active:
	- dev
   #通过 spring.profiles.active 设置当前使用的版本
---
server:
  port: 8001

spring:
  profiles: dev       # 开发环境
  application:
    name: microservice-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/hand_train             # 数据库名称
    username: root
    password: 231023
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservice-dept8001-hystrix   #自定义服务名称信息